# Pregunta 1

##### El broadcasting , lo que permite es realizar operaciones matemáticas con arrays de dimensiones diferentes ampliando los arrays pequeños a la dimensión del array de dimensiones superior. Estas operaciones se producen en C en lugar de Python , sin hacer copias lo que supone un aumento de eficiencia en los algoritmos.
##### Las restricciones del broadcasting ocurren si los tamaños en cada dimensión no coinciden y ninguno es igual a 1, en ese caso se produce un error y la operación es incompatible.
##### Algunos de los ejemplos de broadcasting con numpy son los siguientes:


In [3]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 27, 30])

c = a + b

print(c, 'Se expande el segundo array')

[[11 22 33]
 [14 25 36]] Se expande el segundo array


In [6]:

a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([1, 2, 33])

c = np.array([[100], [200]])

d = a + b + c


print(d)

[[111 122 133]
 [214 225 236]]


# Pregunta 2

##### La eficacia de la memoria mapeada en Numpy se basa en manipular  los datos directamente desde un archivo en el  disco sin tener de cargarlos completamente en memoria , es util sobre todo cuando trabajas con archivo muy pesados.

##### Para comprobar la eficaciade su uso bastaria con crear dos arrays , uno mapeado en memoria y otro normal , aplicar operaciones sobre ellos y comprobar el tiempo de ejecucion de uno frente a otro. 

##### Haciendo esto se comprueba que en efecto el tiempo de ejecucion del array mapeado es menor que el tiempo de ejecucion del array normal.

# Pregunta 3

##### En primera instancia , otros lenguajes o entornos se han utilizado mas que Python para aplicaciones científicas aunque poco a poco Python esta ganando popularidad ante los usuarios gracias a librerías como Numpy , Scipy y Matplotlib entre otras. Esto se debio a la falta de librerías enfocadas a este área. 
##### A pesar de esto ha habido nuevos desarrollos en Pyhon, que intentan captar mas usuarios, pero aun así no consiguen convencer a los programadores para que lo elijan frente a R.
##### Uno de los problemas que tiene Python es el trabajo de datasets con Numpy , que en el caso de R tiene una clase específica para ello y sus librerías fueron creadas teniendo en cuenta ese objeto.
##### El articulo expone cuales son los “avances” o integraciones que se han hecho con Pandas para el análisis de datos estadísticos.
##### A la hora de analizar diferentes lenguajes para este propósito , cada lenguaje destaca en unas cosas frente a los otros, y a la hora de elegir el lenguaje depende del proyecto y con que el usuario prefiere trabajar.
##### R esta diseñado para el análisis estadístico de datos y su punto fuerte es la variedad de librerías creadas para ello y cómo se comporta cuando trabajas en el (número de errores), pero es cierto que es un lenguaje que requiere de conocimiento de programación mas profundos que otros lenguajes como Python.
##### Python es un lenguaje que no se creó específicamente para la ciencia de datos como fue el caso de R pero poco a poco se han ido añadiendo paquetes para este tipo de desarrollos ( los que se mencionan en el artículo) y que con su mayor simplicidad ,por experiencia propia consiguen que los usuarios lo elijan antes que R.
##### En cuanto a SQL es un lenguaje enfocado a trabajar con bases de datos relacionales , para sacar querys y trabajar con grandes volúmenes de datos personalmente es un lenguaje muy sencillo pero está muy limitado exclusivamente a ese tipo de acciones , y con ciertas librerías en Python pudes programar con SQL si asi lo quieres.
##### Lo mismo pasa con lenguajes como por ejemplo SAS, muy parecido a SQL , se utiliza en ciertas empresas pero no creo que sea una opción elegir frente a las tres mencionadas anteriormente.
