In [2]:
import numpy as np
from sklearn.impute import SimpleImputer

In [3]:
# Carga de datos
X_train = [[1,      4], 
           [np.nan, 3], 
           [7,      8]]

In [4]:
# Limpieza de datos: imputación valores ausentes (modelo)
imputer = SimpleImputer(strategy='mean') # Utilizamos la estrategia de la media

# Aplicar los métodos "fit" y "transform" para imputar los valores pérdidos de X_train
# ???
imp= imputer.fit(X_train)

X_train_clean= imp.transform(X_train)

print(X_train_clean)

[[1. 4.]
 [4. 3.]
 [7. 8.]]


In [6]:
# Imputación de valores ausentes sobre el conjunto de test
X_test = [[np.nan, 10], 
          [6,      np.nan], 
          [8,      2]]

# Imputar los datos del conjunto de test
# ???

X_test_clean = imp.transform(X_test)  #Ya tengo el objeto creado

print(X_test_clean)

[[ 4. 10.]
 [ 6.  5.]
 [ 8.  2.]]


In [9]:
import pandas as pd

file_path = 'C:/Users/msi15/Documents/GitHub/Artificial-Intelligence-Dan/5 Aprendizaje Supervisado/Datasets/Clasificacion/penguins.csv'
df = pd.read_csv(file_path, sep=';')
df

CulmenLength  CulmenDepth  FlipperLength  BodyMass  Species
0            39.1         18.7          181.0    3750.0        0
1            39.5         17.4          186.0    3800.0        0
2            40.3         18.0          195.0    3250.0        0
3             NaN          NaN            NaN       NaN        0
4            36.7         19.3          193.0    3450.0        0
..            ...          ...            ...       ...      ...
339          55.8         19.8          207.0    4000.0        2
340          43.5         18.1          202.0    3400.0        2
341          49.6         18.2          193.0    3775.0        2
342          50.8         19.0          210.0    4100.0        2
343          50.2         18.7          198.0    3775.0        2

[344 rows x 5 columns]

In [20]:
data = np.array(df)
print(data)


[[3.910e+01 1.870e+01 1.810e+02 3.750e+03 0.000e+00]
 [3.950e+01 1.740e+01 1.860e+02 3.800e+03 0.000e+00]
 [4.030e+01 1.800e+01 1.950e+02 3.250e+03 0.000e+00]
 ...
 [4.960e+01 1.820e+01 1.930e+02 3.775e+03 2.000e+00]
 [5.080e+01 1.900e+01 2.100e+02 4.100e+03 2.000e+00]
 [5.020e+01 1.870e+01 1.980e+02 3.775e+03 2.000e+00]]
[  3 271]


In [21]:
pos_ausentes= np.unique(np.where(np.isnan(data))[0])

print(pos_ausentes)

[  3 271]


In [22]:
data[271,:]

array([nan, nan, nan, nan,  1.])

In [23]:
imputer= SimpleImputer(strategy='mean')
imp=imputer.fit(data)

data_clean= imp.transform(data)
data_clean

array([[3.910e+01, 1.870e+01, 1.810e+02, 3.750e+03, 0.000e+00],
       [3.950e+01, 1.740e+01, 1.860e+02, 3.800e+03, 0.000e+00],
       [4.030e+01, 1.800e+01, 1.950e+02, 3.250e+03, 0.000e+00],
       ...,
       [4.960e+01, 1.820e+01, 1.930e+02, 3.775e+03, 2.000e+00],
       [5.080e+01, 1.900e+01, 2.100e+02, 4.100e+03, 2.000e+00],
       [5.020e+01, 1.870e+01, 1.980e+02, 3.775e+03, 2.000e+00]])

In [24]:
pos_ausentes= np.unique(np.where(np.isnan(data_clean))[0])
print(pos_ausentes)

[]


In [26]:
data_clean[271,:]

array([4.39219298e+01, 1.71511696e+01, 2.00915205e+02, 4.20175439e+03,
       1.00000000e+00])