In [6]:
from sklearn import preprocessing
import numpy as np

In [7]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [8]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()


# Estandarizamos los datos de entrenamiento
# ???

X_train_scaled = scaler.fit_transform(X_train)

print(X_train_scaled)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [9]:
X_train_2 = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [10]:
# Aplicamos los métodos "fit" y "transform" por separado
# ???
# ???
scaler = standardizer.fit(X_train_2)   #objeto creado con los datos de train para luego utilizarlo en test

X_train_2_scaled = scaler.transform(X_train_2)

print(X_train_2_scaled)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [11]:
# Comprobar si las matrices estandarizadas son iguales
# ???
print(np.array_equiv( X_train_scaled , X_train_2_scaled ))

True
