# Examen Primera Convocatoria

In [60]:
# Your imports HERE !!!!
import numpy as np
import pandas as pd
from typing import List

## 01 - 1 pt
- Dado un array de elementos, escribir una función, que reciba dicho array como parámetro de entrada y devuelva el elemento repetido. Usando plain Python, sin ninguna librería.

In [87]:
fibonacci_lambda = lambda n: reduce(lambda x,y: x + [x[-1] + x[-2]], range(n-2), [0,1])

In [7]:
array_src = [4, 8, 0, 3, 6, 2, 1, 5, 3, 9, 7]
expected_rep_element = 3
rep_element = repeated_element(array_src) # This calls your function repeated_element
assert(expected_rep_element == rep_element)  # This will fail if the element is not found correctly

In [6]:
# Your solution HERE !!!!
def repeated_element(input_array: np.ndarray):
    visited_elements = []
    for element in input_array:
        if element not in visited_elements:
            visited_elements.append(element)
        else:
            return element
        

## 02 - 1pt
- Genera una matriz con valores aleatorios de 0 a 100 de dimensiones 16x16
- Calcula los siguentes estadísticos en la matriz anterior, por fila (el resultado de cada uno debe ser un array de dimensiones 1x16)
  - Suma de los elementos de cada fila
  - Media de los elementos de cada fila
  - Valores mínimos de cada fila
  - Valores máximos de cada fila

In [10]:
# Your solution HERE !!!!
array = np.random.randint(0, 101, (16,16))
print(array)
print(array.shape)

[[69 76 88 85 30 18 19 78  6 77 10 21 25 50 92 19]
 [62 78 12 37 13 81 43 74 84 91 20 30 34 86 50 72]
 [30 87 44 42 98 90 33 27  4 82 57 32 66 78 24 88]
 [13 22 70 73 74  9 26 88 14 61 69  1 44 19 16 38]
 [ 8 24 11 70 31 57 53 76 47 19 58 74 74 77 15 82]
 [21 93 10 58 97  2 20 43 75 71 39 31 77 73 34 75]
 [33 50  6 38 17 73 58 44 92 96  9 11  1 86 62  6]
 [37 26 31 63 73  2 61 43  5 33 50 65 47  6 59 20]
 [92 57  3 85 33 86 15 79 47 49 45 35 68 25 36 74]
 [55 21 22 62 24 83 36 41 67  8  6 29  4 90 48  0]
 [59  3 24 18 35 90 38 83 26 50 19 89 11 13 65 69]
 [30 87 32 16 47 29 65 55 20 25 83 12 54 70 86 47]
 [49  1 62 41 36 79  6 55 51 88 32 60 18 63 38 24]
 [99 93 15  7 68 30 54 60 27 84 29 91 53 55 48 31]
 [31 97 19 33 39 98 34 95 61 14 66 80 19 63 62 19]
 [ 7 48 43  7 84 40 97 58 38 52 82 28 92 19 94 42]]
(16, 16)


In [23]:
# Suma de los elementos de cada fila
array_sum_filas = np.sum(array, axis=1).reshape(16,1)
array_sum_filas.shape


(16, 1)

In [26]:
array_media = np.mean(array, axis=1).reshape(16,1)
array_media

array([[47.6875],
       [54.1875],
       [55.125 ],
       [39.8125],
       [48.5   ],
       [51.1875],
       [42.625 ],
       [38.8125],
       [51.8125],
       [37.25  ],
       [43.25  ],
       [47.375 ],
       [43.9375],
       [52.75  ],
       [51.875 ],
       [51.9375]])

In [27]:
array_min = np.min(array, axis=1).reshape(16,1)
array_min

array([[ 6],
       [12],
       [ 4],
       [ 1],
       [ 8],
       [ 2],
       [ 1],
       [ 2],
       [ 3],
       [ 0],
       [ 3],
       [12],
       [ 1],
       [ 7],
       [14],
       [ 7]])

In [28]:
array_max = np.max(array, axis=1).reshape(16,1)
array_max

array([[92],
       [91],
       [98],
       [88],
       [82],
       [97],
       [96],
       [73],
       [92],
       [90],
       [90],
       [87],
       [88],
       [99],
       [98],
       [97]])

## 03 - 1pt

- Generar un dataframe de 3x4 dimensiones con valores númericos aleatorios [0,10]
- Darle un índice semántico alfanumérico
- Aplicarle una función lambda que obtenga la diferencia entre el máximo y mínimo de cada fila

In [29]:
# Your solution HERE !!!!
input_array = np.random.randint(0,11, (3,4))
df = pd.DataFrame(input_array, index=['a', 'b', 'c'])
df

0   1  2   3
a  8   4  8   6
b  6   3  6   2
c  8  10  8  10

In [36]:
np.max(df.iloc[0])

8

In [37]:
df.apply(lambda row: np.max(row) - np.min(row), axis=1)

a    4
b    4
c    2
dtype: int32

## 04 - 1pt
- Crear un array de NumPy de dimensiones 8x5, con números enteros aleatorios en el rango [-100, 100]
- Ejecutar en este orden
  - Reemplazar valores  
    - Reemplazar los valores de todos aquellos números múltiplos de 5 por 100
    - Reemplazar los valores de todos aquellos números múltiplos de 3 por Nan
   
  - Averiguar cuantos elementos tienen Nan por fila
  - Reemplazar los valores de Nan por 0

In [41]:
# Your solution HERE !!!!
input_array = np.random.randint(-100, 101, (8,5))
input_array

array([[ 19, -36,  60, -11,  -8],
       [ 58, -95,  22, -91, -73],
       [-14,  91,  20,  80, -42],
       [ 30,  81,  -9, -30,  26],
       [-64,  25,  14, -44,  79],
       [ 72, -56, -27, -88, -20],
       [-79, -79,  -5,  83,  15],
       [ 14, -65,   7, -22,  64]])

In [44]:
np.where(input_array % 5 == 0, 100, input_array)

array([[ 19, -36, 100, -11,  -8],
       [ 58, 100,  22, -91, -73],
       [-14,  91, 100, 100, -42],
       [100,  81,  -9, 100,  26],
       [-64, 100,  14, -44,  79],
       [ 72, -56, -27, -88, 100],
       [-79, -79, 100,  83, 100],
       [ 14, 100,   7, -22,  64]])

In [55]:
nans = np.where(input_array % 3 == 0, np.nan, input_array)
nans

array([[ 19.,  nan,  nan, -11.,  -8.],
       [ 58., -95.,  22., -91., -73.],
       [-14.,  91.,  20.,  80.,  nan],
       [ nan,  nan,  nan,  nan,  26.],
       [-64.,  25.,  14., -44.,  79.],
       [ nan, -56.,  nan, -88., -20.],
       [-79., -79.,  -5.,  83.,  nan],
       [ 14., -65.,   7., -22.,  64.]])

In [58]:
np.count_nonzero(np.isnan(nans), axis=1).reshape(8,1)

array([[2],
       [0],
       [1],
       [4],
       [0],
       [2],
       [1],
       [0]], dtype=int64)

In [59]:
np.where(np.isnan(nans), 0, nans)

array([[ 19.,   0.,   0., -11.,  -8.],
       [ 58., -95.,  22., -91., -73.],
       [-14.,  91.,  20.,  80.,   0.],
       [  0.,   0.,   0.,   0.,  26.],
       [-64.,  25.,  14., -44.,  79.],
       [  0., -56.,   0., -88., -20.],
       [-79., -79.,  -5.,  83.,   0.],
       [ 14., -65.,   7., -22.,  64.]])

## 05 - 1pt
- Crear una función que reciba una lista de strings y devuelva una serie de pandas, y convierta el primer y último carácter de la palabra de cada elemento de la serie a mayúsculas

In [86]:
languages = ['python', 'php', 'java', 'javascript', 'c++', 'sql']
expected_output = pd.Series(['PythoN', 'PhP', 'JavA', 'JavascripT', 'C++', 'SqL'])
output = first_last_uppercase(languages)  # This calls your function first_last_uppercase
assert(expected_output.equals(output))  # This will fail if the two lists are different

0        PythoN
1           PhP
2          JavA
3    JavascripT
4           C++
5           SqL
dtype: object


In [84]:
# Your solution HERE !!!!
def first_last_uppercase(input_list: List[str]) -> pd.Series:
    input_series = pd.Series(input_list)
    input_series= input_series.apply(lambda x: x[0].upper()+x[1:-1]+x[-1].upper())
    print(input_series)
    return input_series
    

## 06 - 3 pt
- Se tienen cuatro datasets, se adjuntan sus datos como diccionarios
  - Orders, representa un conjunto de pedidos, con sus fechas, su cantidad, y el cliente y vendedor asociados al mismo
  - Customers, conjunto de clientes, con su nombre y su ciudad
  - Salesman, conjunto de vendedores, con su nombre, ciudad y porcentaje de comisión por venta
  - Cities, conjunto de ciudades con sus nombres
- Obtener la siguiente información usando Pandas
  - El nombre del vendedor con la mejor venta, y a que cliente ha sido
  - Dinero de la comisión otorgada para cada pedido, ordenado por fechas
  - Media del dinero de los pedidos de los clientes de Tokyo
  - Total del dinero de las comisiones del vendedor Ikuzu Midoriya en el mes de Agosto
- Representar graficamente
  - Media del total de cada pedido para cada cliente agrupado por ciudad
  - Línea temporal del total de los pedidos

In [ ]:
orders = {'OrderId': [1,2,3,4,5,6], 'OrderDate': ['2021-07-23', '2021-08-06', '2021-07-28', '2021-08-04', '2021-08-03', '2021-07-30'], 'Amount': [1500.5,2000.65,1550.2,1900.75,2205.4, 1208.22], 'CustomerId': [3,4,2,2,1,4], 'SalesmanId': [3,3,2,1,3,2]}
customers = {'CustomerId': [1,2,3,4], 'Name': ['Brad Davis', 'Julian Green', 'Geoff Cameron', 'Fabian Johnson'], 'CityId': [2,1,2,3]}
salesmans = {'SalesmanId': [1,2,3], 'Name': ['James Knite', 'Reinhardt Wilhelm', 'Ikuzu Midoriya'], 'CityId': [1,3,2], 'Comission': [0.15,0.11,0.09]}
cities = {'CityId': [1,2,3], 'Name': ['New York', 'Tokyo', 'Berlin']}

In [ ]:
# Your solution HERE !!!!

## 07 - 1pt
- Escribir un generador `frange` que simule el comportamiento de la función `arange` de NumPy
- Esta función cada vez que se invoque debe devolver valores espaciados uniformemente a partir de un valor inicial. Se debe proveer a dicha función un valor inicial para la secuencia de números y un valor para el step
- Debe soportar valores númericos en coma flotante
- La función potencialmente se puede llamar un número infinito de veces
- Usando plain Python, sin ninguna librería

In [ ]:
import math

init = 10.6
step = 0.8
g = frange(init, step)  # This calls your function frange

iters = 10
numbers = [next(g) for n in range(iters)]
for i, n in enumerate(numbers):
    assert(math.isclose(n, init + (step * i)))  # This will fail if the range is not properly created

In [ ]:
# Your solution HERE !!!!

## 08 - 1pt
- Crear una lista de meses de Enero a Diciembre (eje X)
- Generar datos aleatorios para el eje Y, hacerlo 3 veces distintas (Y0, Y1 e Y2)
- Representar las 3 secuencias de datos aleatorios en una sola figura usando matplotlib
- Añadir una leyenda para poder identificar cada secuencia
- Nombrar las 3 secuencias de la siguiente manera ("Facebook", "Twitter", "Instagram")
- Añadir un título y nombres a los dos ejes
- Añadir una anotación (texto y flecha) a uno de los gráficos

In [ ]:
# Your solution HERE !!!!