# Examen Demo

In [1]:
# Your imports HERE !!!!
import numpy as np
import pandas as pd


## 01
- La serie de Fibonacci es una sucesión de números, en la cual cada número es la suma de los dos anteriores. Los dos primeros son siempre 0 y 1.
  - $F_0 = 0$
  - $F_1 = 1$
  - $F_n = F_{n-1} + F_{n-2}$
- Crear una serie de Fibonacci hasta un número *n* usando una función lambda.

In [ ]:
expected_fibo_serie = [0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597]
fibo_serie = fibonacci_lambda(len(expected_fibo_serie))  # This calls your lambda function fibonacci_lambda
assert(expected_fibo_serie == fibo_serie)  # This will fail if the serie is not correct

NameError: ignored

In [ ]:
# Your solution HERE !!!!
n=len(expected_fibo_serie)
def fibonacci_lambda(n):
  f0=0
  f1=1
  pos0=0
  pos1=1
  c=2
  fibo_serie=[f0,f1]
  while c<n:
    n1=fibo_serie[pos0]
    n2=fibo_serie[pos1]
    fibo_serie.apply(n1+n2)
    pos0+=1
    pos1+=1
    c+=1
  return fibo_serie

fibo_serie = fibonacci_lambda(len(expected_fibo_serie))  # This calls your lambda function fibonacci_lambda
print(fibo_serie)
assert(expected_fibo_serie == fibo_serie)  # This will fail if the serie is not correct


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597]


## 02
- Crear una función que reciba un array de NumPy y devuelva otro en el cual estén marcados como True los elementos duplicados (a partir de la segunda ocurrencia), y como False los no repetidos o las primeras ocurrencias de los duplicados.

In [ ]:
numbers = np.array([4, 4, 4, 3, 8, 1, 9, 6, 1, 5, 9, 4, 0, 2])
expected_output = np.array([False, True, True, False, False, False, False, False, True, False, True, True, False, False])
#output = find_duplicates(numbers)   # This calls your function find_duplicates
#assert(np.array_equal(expected_output, output))  # This will fail if the result is not as expected

In [ ]:
# Your solution HERE !!!!
def find_duplicates(numbers):
  output=np.array([])
  dup=[]
  uni=[]

  for i in numbers:

    if i not in uni:
        uni.append(i)
        output= np.append(output,False)
        #print(output)

    elif i not in dup:
        dup.append(i)
        output=np.append(output,True)
        #print(output)

    elif i in dup:
        output=np.append(output,True)
        #print(output)
  #print(dup)
  return output


#print(output)

output = find_duplicates(numbers) 
print(output)  # This calls your function find_duplicates
assert(np.array_equal(expected_output, output))  # This will fail if the result is not as expected

[0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0.]


## 03
- Resolución de dos sistemas de ecuaciones
    - $ A : \begin{cases} -9x +  4y = 20 \\ -7y + 16x = 80                         \end{cases}$
    
    - $ B : \begin{cases} x - 2y + 3z = 7 \\ 2x + y + z = 4 \\ -3x + 2y -2z = -10 \end{cases}$
- Verifica por código los resultados

In [5]:
# Your solution HERE !!!!
#A)
import numpy.linalg as linalg
A= np.matrix([[-9,4],[-7,16]])
B= np.matrix([[20],[80]])
X= A**(-1)*B
print(X)
x , y  = linalg.solve(A,B)
print(x,y)
C= np.matrix([[1,-2,3],[2,1,1],[-3,3,-2]])
D= np.matrix([[7],[4],[-10]])
Y= C**(-1)*D
print(Y)

[[0.]
 [5.]]
[[-0.]] [[5.]]
[[ 1.75]
 [-0.75]
 [ 1.25]]


## 04
- Crear un objeto Series con 10 elementos, que contenga más de un tipo básico, con índices de tipo string
- Demuestra que los datos con índices posicionales son los mismos que los obtenidos con índices semánticos, seleccionando a través de slicing, al menos 4 elementos de la serie anterior

In [24]:
# Your solution HERE !!!!
serie = pd.Series(list(['a',1,2,True,'b',5,6,7,8,9]), index=['i1','i2','i3','i4','i5','i6','i7','i8','i9','i10'])
print(serie)

i1        a
i2        1
i3        2
i4     True
i5        b
i6        5
i7        6
i8        7
i9        8
i10       9
dtype: object


In [26]:
serie['i2':]

i2        1
i3        2
i4     True
i5        b
i6        5
i7        6
i8        7
i9        8
i10       9
dtype: object

## 05
- Crear un DataFrame de dimensiones 10x10, con números aleatorios en el rango `[0,20]`
- Reemplazar todos aquellos elementos menores de 5 por NaN
- Averiguar cuantos elementos tienen Nan por fila

In [ ]:
# Your solution HERE !!!!
data = np.random.randint(0,21, size = (10,10))
df=pd.DataFrame(data)
print(df)

df = df.replace(df[df<5],)


print(df)

    0   1   2   3   4   5   6   7   8   9
0   7  16  19   9   7  20   5  13  12  16
1  14  15   2   1   2  18   2   4  10  11
2   3  18  12   5   5   0  18   4   9  19
3   3   9   4   8   2  12  14   7  18  15
4  17   0   9  17   3  11  12  12  15   9
5   9   9  19  12  13  15  19  18   4   5
6  15   4   6  12   6   4  17   8  16  16
7   1   2  11  10  18  10   3  18  13  18
8   4   6  16  14   4  10   0  10   8   0
9  12   5  15  17  18  15   6  11  16  18
      0     1     2     3     4     5     6     7     8     9
0   1.0  16.0  19.0   NaN   NaN  20.0   NaN  13.0  12.0  16.0
1  14.0  15.0   NaN   1.0   NaN  18.0   NaN   NaN  10.0  11.0
2   3.0  18.0  12.0   NaN   NaN   NaN  18.0   NaN   NaN  19.0
3   3.0   NaN   NaN   NaN   NaN  12.0  14.0   NaN  18.0  15.0
4  17.0   NaN   NaN  17.0   2.0  11.0  12.0  12.0  15.0   NaN
5   NaN   NaN  19.0  12.0  13.0  15.0  19.0  18.0   NaN   NaN
6  15.0   0.0   NaN  12.0   NaN   NaN  17.0   NaN  16.0  16.0
7   NaN   NaN  11.0  10.0  18.0  10.0   Na

In [ ]:
num_nulos_por_fila = df.isna().sum(axis=1)

## 06
- Dada una lista de elementos, crea una función que devuelva un dataframe sin los elementos duplicados

In [19]:
serie = ['a','b','c','a','c','a','g']
expected_output = pd.DataFrame(['a','b','c','g'])
#output = remove_duplicates(serie)   # This will call tour function remove_duplicates
#assert(expected_output.equals(output))  # This will fail if the result is not as expected

In [21]:
# Your solution HERE !!!!
def remove_duplicates(serie):
    df=pd.DataFrame(serie)
    df=df.drop_duplicates().reset_index(drop=True)
    return df

output = remove_duplicates(serie)
print(output)
assert(expected_output.equals(output))

   0
0  a
1  b
2  c
3  g


## 07 - 1pt
- Escribir un generador `frange` que simule el comportamiento de la función `arange` de NumPy
- Esta función cada vez que se invoque debe devolver valores espaciados uniformemente a partir de un valor inicial. Se debe proveer a dicha función un valor inicial para la secuencia de números y un valor para el step
- Debe soportar valores númericos en coma flotante
- La función potencialmente se puede llamar un número infinito de veces
- Usando plain Python, sin ninguna librería

In [ ]:
import math

init = 10.6
step = 0.8
g = frange(init, step)  # This calls your function frange

iters = 10
numbers = [next(g) for n in range(iters)]
for i, n in enumerate(numbers):
    assert(math.isclose(n, init + (step * i)))  # This will fail if the range is not properly created

In [ ]:
# Your solution HERE !!!!
def frange(start, step=1.0):
    current = start
    while True:
        yield current
        current += step
        
numbers = frange(0.0, 0.5)
for _ in range(10):
    print(next(numbers))

## 08
- Crear una función que reciba una Serie de Pandas y devuelva esa misma serie, reemplazando los espacios en blanco por el carácter menos frecuente en dicha serie.

In [ ]:
serie = pd.Series(list('bba cabc faabba aacbbfe'))
expected_output = pd.Series(list('bbaecabcefaabbaeaacbbfe'))
output = clean_whitespace_replace(serie)  # This calls your function clean_whitespace_replace
assert(expected_output.equals(output))  # This will fail if result is not as expected

In [ ]:
# Your solution HERE !!!!
serie = pd.Series(list('bba cabc faabba aacbbfe'))
print(serie)

a =serie.value_counts()
print(a)


0     b
1     b
2     a
3      
4     c
5     a
6     b
7     c
8      
9     f
10    a
11    a
12    b
13    b
14    a
15     
16    a
17    a
18    c
19    b
20    b
21    f
22    e
dtype: object
b    7
a    7
     3
c    3
f    2
e    1
dtype: int64


pandas.core.series.Series

In [ ]:
vmax=''
valor=0
for k, v in a.items():
  if v>valor:
    valor=v
    vmax=k
print(vmax, valor)
serie=serie.replace(' ',vmax)

print(serie)

b 7
0     b
1     b
2     a
3     b
4     c
5     a
6     b
7     c
8     b
9     f
10    a
11    a
12    b
13    b
14    a
15    b
16    a
17    a
18    c
19    b
20    b
21    f
22    e
dtype: object


In [ ]:
import pandas as pd
import json

# Abrir el archivo JSON
with open('archivo.json', 'r') as f:
    data = json.load(f)

# Convertir el JSON a un DataFrame
df = pd.DataFrame(data)

# Mostrar el DataFrame
print(df)



# Ruta del archivo JSON
ruta_archivo = 'ruta/del/archivo/archivo.json'

# Abrir el archivo JSON
with open(ruta_archivo, 'r') as f:
    data = json.load(f)

# Convertir el JSON a un DataFrame
df = pd.DataFrame(data)

# Mostrar el DataFrame
print(df)
Asegúrate de reemplazar 'ruta/del/archivo/archivo.json' con la ruta y nombre de archivo correctos en tu sistema. Esto permitirá que Python encuentre y abra el archivo JSON especificado. Luego, el resto del código es el mismo que se mencionó en la respuesta anterior. El JSON se carga en la variable data y se convierte en un DataFrame utilizando pd.DataFrame(data). Por último, el DataFrame se imprime utilizando print(df).






