In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
import time

En esta celda se crea una matriz $nxn$ aleatoria para trabajar con los siguientes ejercicios

In [2]:

#Matriz de trabajo aleatoria
a = np.random.randint(0,9, size=(3,3))
print(a,'\n')
print(len(a),'\n')


[[4 3 5]
 [1 0 5]
 [8 5 4]] 

3 



In [3]:
def isSquare (m):
  for row in m:
    if len(row)== len(m):
      return True
print(isSquare(a))

True


**Ejercicio 1)**

In [4]:
#1a)

def laplace_det(matrix):
    n = matrix.shape[0] 
    
    # matriz 1x1
    if n == 1:
        return matrix[0, 0]
    
    det_matrix = 0  # Det inicializado a 0
    
    for j in range(n):
        #print('Matriz que tomo:\n',np.delete(np.delete(matrix, 0, 0), j, 1),'\n')
        
        cofactor = (-1) ** j * laplace_det(np.delete(np.delete(matrix, 0, 0), j, 1)) #Borro filas coluumnas quedandome con lo que borro
        
        det_matrix += matrix[0, j] * cofactor
    
    return det_matrix


print('det= ',laplace_det(a))

det=  33


In [5]:
#1b)

A=np.array([[1,2,-6],[0,0,3],[0,0,4]])
print(A)


det =1
for k in range(len(A)):
  det*=A[k][k]            #Multiplicacion de los elementos de la diagonal

print('Det= ', det)


[[ 1  2 -6]
 [ 0  0  3]
 [ 0  0  4]]
Det=  0


In [6]:
# 1C.1)

B=a  #Matriz del primer bloque
print(B)

print('det= ', round(np.linalg.det(a)),'\n')
B[[0, 1]] = B[[1, 0]]

print(B)
print('det= ', round(np.linalg.det(a)))
#Intercambiando filas/ columnas cambia el signo del determinante.

[[4 3 5]
 [1 0 5]
 [8 5 4]]
det=  33 

[[1 0 5]
 [4 3 5]
 [8 5 4]]
det=  -33


In [7]:
#1C.2)


print(a,'\n')
det_inicial = np.linalg.det(a)
print("Determinante inicial:", round(det_inicial))

# fila + fila
a[2] = a[2] + a[0]
det_suma = np.linalg.det(a)
print("Determinante después de la suma:", round(det_suma))

# fila por otra fila multiplicada por un escalar
a[2] = a[2] + 2 * a[0]

det_suma_escalar = np.linalg.det(a)
print("Determinante después de la suma * escalar:", round(det_suma_escalar))

#sumar una combinación lineal de filas (o columnas) no cambian el determinante.

[[1 0 5]
 [4 3 5]
 [8 5 4]] 

Determinante inicial: -33
Determinante después de la suma: -33
Determinante después de la suma * escalar: -33


**Eliminación Gauss**

Para el convertir la matriz en una triangular inferior , se ha hecho la eliminacion gauss para convertirla en una triangular superior y posteriormente se ha transpuesto la matriz , ya que esa transformacion no afecta al coste computacional.

In [8]:
#1D)
import numpy as np

def eliminacion_gauss(A):
    A = A.astype('float64')  #matriz a float
    
    m, n = A.shape
    for i in range(m):
        # Encuentra el pivote máximo en la columna actual
        pivot_row = np.argmax(np.abs(A[i:, i])) + i
        
        # Intercambia filas si es necesario
        if pivot_row != i:
            A[[i, pivot_row]] = A[[pivot_row, i]]
        
        # Aplica eliminación gaussiana a las filas siguientes
        for j in range(i+1, m):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
                        
    print(A)
    A=A.T      
            
    return A

matriz_triangular = eliminacion_gauss(a)
#print(a)
print(matriz_triangular,'\n\n')

[[11.          5.         19.        ]
 [ 0.          1.18181818 -1.90909091]
 [ 0.          0.          2.53846154]]
[[11.          0.          0.        ]
 [ 5.          1.18181818  0.        ]
 [19.         -1.90909091  2.53846154]] 




In [9]:
#1E)

def determinante_gauss(A):
    A = A.astype('float64')  #matriz a float
    
    m, n = A.shape
    for i in range(m):
        
        pivot_row = np.argmax(np.abs(A[i:, i])) + i
        
        if pivot_row != i:
            A[[i, pivot_row]] = A[[pivot_row, i]]
        
        for j in range(i+1, m):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
                       
    #print(A)
    A=A.T        
    det =1
    for k in range(len(A)):
      det*=A[k][k]
    return det

print('Det= ', round(determinante_gauss(matriz_triangular)))

Det=  -33


**Para comprobar como varia la complejidad computacional en funcion del tamaño de la matriz basta con ajustar la matriz inicial del documento**

In [10]:
#1F)

print('Complejidad computacional gauss = ', len(a)**3)
print('Complejidad computacional eliminacion recursiva Laplace= ', math.factorial(len(a)), '\n' )

Complejidad computacional gauss =  27
Complejidad computacional eliminacion recursiva Laplace=  6 



**Es mas optimo utilizar la eliminacion de gauss a medida que las matrices son mas grandes**

In [11]:
#1G)


def comparacion_tiempos():
    
    for i in range (2,11):
        a=np.random.rand(i,i)
        
        inicio_1 = time.time()
        laplace_det(a)
        fin_1 = time.time()
        tiempo_1 = (fin_1 - inicio_1)*1e6
        

        inicio_2 = time.time()
        determinante_gauss(a)
        fin_2 = time.time()
        tiempo_2 = (fin_2 - inicio_2)*1e6


        inicio_3 = time.time()
        np.linalg.det(a)
        fin_3 = time.time()
        tiempo_3 = (fin_3 - inicio_3)*1e6


        print("Tiempo de ejecución de Laplace:", tiempo_1, "microsegundos")
        print("Tiempo de ejecución de Gauss:", tiempo_2, "microsegundos")
        print("Tiempo de ejecución de funcion predeterminada:", tiempo_3, "microsegundos")
        print(f'\n Matrices {i}x{i}\n\n')

In [12]:
comparacion_tiempos()

Tiempo de ejecución de Laplace: 0.0 microsegundos
Tiempo de ejecución de Gauss: 0.0 microsegundos
Tiempo de ejecución de funcion predeterminada: 996.8280792236328 microsegundos

 Matrices 2x2


Tiempo de ejecución de Laplace: 0.0 microsegundos
Tiempo de ejecución de Gauss: 996.3512420654297 microsegundos
Tiempo de ejecución de funcion predeterminada: 0.0 microsegundos

 Matrices 3x3


Tiempo de ejecución de Laplace: 2993.345260620117 microsegundos
Tiempo de ejecución de Gauss: 0.0 microsegundos
Tiempo de ejecución de funcion predeterminada: 0.0 microsegundos

 Matrices 4x4


Tiempo de ejecución de Laplace: 9816.884994506836 microsegundos
Tiempo de ejecución de Gauss: 0.0 microsegundos
Tiempo de ejecución de funcion predeterminada: 0.0 microsegundos

 Matrices 5x5


Tiempo de ejecución de Laplace: 26467.323303222656 microsegundos
Tiempo de ejecución de Gauss: 998.9738464355469 microsegundos
Tiempo de ejecución de funcion predeterminada: 0.0 microsegundos

 Matrices 6x6


Tiempo de ejecu